### ISSUE TITLE
please help

### ISSUE THREAD

**Issue by BruteForceBTC** [meesvw/bitcoin-bruteforce#22]
Hello, 

How are you ? I really like your project ,  but i   am not a developer or something. I have python3 and have like no clue how to run this on my mac. Have been busy with it for 2 days now and really like understand 0%

please van you make this like for dummies also, just click click and start brute forcing wallets dummyproof

praat je toevallig nederlands Mees dan kunnen en op telegram ofzo even verder praten. Je hulp is echt nodig, grote dank

**Comment by meesvw** [comment]
Hey I can help, could you give me some more information where you're getting stuck? Like errors or other problems you encounter?

**Comment by spyder403** [comment]
raise ValueError('unsupported hash type ' + name)
  File "/usr/lib/python3.10/hashlib.py", line 166, in __hash_new
    return __get_builtin_constructor(name)(data)
  File "/usr/local/lib/python3.10/dist-packages/bit/crypto.py", line 19, in ripemd160_sha256
    return new('ripemd160', sha256(bytestr)).digest()
  File "/usr/local/lib/python3.10/dist-packages/bit/crypto.py", line 19, in ripemd160_sha256
    return new('ripemd160', sha256(bytestr)).digest()
ValueError: unsupported hash type ripemd160
  File "/usr/local/lib/python3.10/dist-packages/bit/crypto.py", line 19, in ripemd160_sha256
    return new('ripemd160', sha256(bytestr)).digest()
  File "/usr/lib/python3.10/hashlib.py", line 166, in __hash_new
    return __get_builtin_constructor(name)(data)
  File "/usr/lib/python3.10/hashlib.py", line 123, in __get_builtin_constructor
    raise ValueError('unsupported hash type ' + name)
ValueError: unsupported hash type ripemd160
  File "/usr/lib/python3.10/hashlib.py", line 123, in __get_builtin_constructor
    raise ValueError('unsupported hash type ' + name)
  File "/usr/lib/python3.10/hashlib.py", line 166, in __hash_new
    return __get_builtin_constructor(name)(data)
  File "/usr/lib/python3.10/hashlib.py", line 166, in __hash_new
    return __get_builtin_constructor(name)(data)
  File "/usr/lib/python3.10/hashlib.py", line 166, in __hash_new
    return __get_builtin_constructor(name)(data)
  File "/usr/lib/python3.10/hashlib.py", line 123, in __get_builtin_constructor
    raise ValueError('unsupported hash type ' + name)
ValueError: unsupported hash type ripemd160
ValueError: unsupported hash type ripemd160
  File "/usr/lib/python3.10/hashlib.py", line 123, in __get_builtin_constructor
    raise ValueError('unsupported hash type ' + name)
  File "/usr/lib/python3.10/hashlib.py", line 123, in __get_builtin_constructor
    raise ValueError('unsupported hash type ' + name)
  File "/usr/lib/python3.10/hashlib.py", line 123, in __get_builtin_constructor
    raise ValueError('unsupported hash type ' + name)
ValueError: unsupported hash type ripemd160
ValueError: unsupported hash type ripemd160
ValueError: unsupported hash type ripemd160
ValueError: unsupported hash type ripemd160

**Comment by meesvw** [comment]
What device are you using to run this script ?

**Comment by BruteForceBTC** [comment]
i just dont understand howto run a program

i have opened terminal, typed python3

and the pasted the code

and nothing happens

**Comment by meesvw** [comment]
Since you cannot provide me with the OS you're using I will give a general explanation. You will first need to download the [bruteforce.py](https://github.com/meesvw/bitcoin-bruteforce/blob/main/bruteforce.py) file. And put it somewhere in a folder. After you've done that you can open your terminal, navigate to the folder containing the [bruteforce.py](https://github.com/meesvw/bitcoin-bruteforce/blob/main/bruteforce.py) file and type: `python3 main.py`.

If you get any errors saying missing packages you should also put the requirements in the same folder as the [bruteforce.py](https://github.com/meesvw/bitcoin-bruteforce/blob/main/bruteforce.py) and type the following in your console: `pip install -r requirements.txt` or `pip3 install -r requirements.txt`. If both don't work you will need to install `pip` this can vary depending on your OS.

**Comment by BruteForceBTC** [comment]
i have macmini os is macventura

**Comment by Qmig** [comment]
> Hey I can help, could you give me some more information where you're getting stuck? Like errors or other problems you encounter?

**Comment by hotdogmeatcake** [comment]
could not find platform independent libraries and idea on getting through this on windows ?

**Comment by Bfbtc** [comment]
hello thanks for your help. I can get a windows laptop but u can not run this on a Mac is what I understand?? Why not?

Maybe u can add me on telegram for quicker help because I dnont understand. username is Zaniizan

help is very much appreciated

I believe in this project maybe we can create like a community on telegram or something

sorry for. my English

**Comment by Bfbtc** [comment]
Can i run this on rasberry pi?

Please someone Who knows what they r doing help thank u

**Comment by meesvw** [comment]
I will close this as no further activity has occured.
